# Generated by Django 2.2 on 2021-02-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
