# Generated by Django 2.2 on 2021-02-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.CharField(max_length=500),
        ),
    ]
