# Generated by Django 2.2 on 2021-02-18 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210215_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detailsTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
