# Generated by Django 2.2 on 2021-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_post_detailstitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=300)),
                ('tipo', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('img', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('detailsTitle', models.CharField(max_length=500)),
            ],
        ),
    ]
